matrix:
  include:
    - language: generic
      notifications:
        email: false
      addons:
        apt:
          packages:
            - aspell
            - aspell-en
            - dictionaries-common
      script:
        - ./check-spelling.sh

    - language: generic
      notifications:
        email: false
      before_install:
        - curl -Lo antidote.tar.gz https://github.com/nre-learning/antidote-core/releases/download/v0.6.2/antidote-linux-amd64.tar.gz && tar xvzf antidote.tar.gz
      install:
        - ./antidote validate .
        - ./check-changelog.sh
      sudo: false
      after_success:
        - ./request-preview.sh
