---
lessonName: Ansible for Network Automation
category: devops
tier: prod

utilities:
- name: linux
  image: antidotelabs/utility

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1
- name: vqfx2
  image: antidotelabs/vqfx:snap2
- name: vqfx3
  image: antidotelabs/vqfx:snap3

connections:
- a: vqfx1
  b: vqfx2
  subnet: 10.12.0.0/24
- a: vqfx2
  b: vqfx3
  subnet: 10.23.0.0/24
- a: vqfx3
  b: vqfx1
  subnet: 10.31.0.0/24
- a: vqfx1
  b: vqfx2
  c: vqfx3
  d: linux
  subnet: 10.1.0.0/24

stages:
  - id: 1
    description: Install Ansible
  - id: 2
    description: Create Inventory and Playbook
  - id: 3
    description: Run playbook
